### PR TITLE
Clarify installation process

### PR DESCRIPTION
**Pull request by alexmourachko**
## Why ?

In the context of the [MT Marathon 2022 organized in Prague](https://ufal.mff.cuni.cz/mtm22/), we are organizing a small project around LASER and stopes. Some participants got confused while trying to install stopes on their machines.

## How ?

Added a very short snippet to cd out of the fairseq folder, clone stopes and then pip install in editable mode.

## Test plan

N/A

### CODE REVIEW

**Review by heffernankevin — APPROVED** [review]

**Comment by nicholas-entis** [comment]
Hi. Thanks for clarifying the installation steps. Unfortunatly, I still encounter the following error: 

FileNotFoundError: [Errno 2] No such file or directory: 'stopes/pipelines/monolingual/conf/dedup/dedup_files.yaml'

Do you have any suggestions on how I could resolve this problem?

**Comment by heffernankevin** [comment]
> Hi. Thanks for clarifying the installation steps. Unfortunatly, I still encounter the following error:
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'stopes/pipelines/monolingual/conf/dedup/dedup_files.yaml'
> 
> Do you have any suggestions on how I could resolve this problem?

Hi @nicholas-entis, can you share the command you ran?

**Comment by nicholas-entis** [comment]
> 

Thanks for your reply. I first installed fairseq using 

%sh git clone https://github.com/pytorch/fairseq && cd fairseq && git checkout tags/v0.12.1 && pip install --editable ./

and then I attempted to installed stopes using 

%sh git clone https://github.com/facebookresearch/stopes.git && cd stopes && pip install '.[mono]'

I should mention that I am trying to do the installation within a Databricks notebook. It does not seem possible to do the installation in editable mode.

**Comment by nicholas-entis** [comment]
> > Thanks for your reply. I first installed fairseq using
> > %sh git clone https://github.com/pytorch/fairseq && cd fairseq && git checkout tags/v0.12.1 && pip install --editable ./
> > and then I attempted to install stopes using
> > %sh git clone https://github.com/facebookresearch/stopes.git && cd stopes && pip install '.[mono]'
> > I should mention that I am trying to do the installation within a Databricks notebook. It does not seem possible to do the installation in editable mode.
> 
> Hi @nicholas-entis, thanks for the context. You'll need to upgrade pip on your databricks notebook in order to install the library (also in editable in mode). Can you try the following:
> 
> ```
> %sh /databricks/python3/bin/python -m pip install --upgrade pip
> ```
> 
> and then try re-running the install command?
> 
> ```
> %sh git clone https://github.com/facebookresearch/stopes.git && cd stopes && pip install -e '.[mono]'
> ```

I tried your suggestion but got the same error :( I successfully installed pip-22.2.2. I wanted to see if I could do the install in a Google collab notebook, but it seems they don't yet support Python >= 3.8.

**Comment by heffernankevin** [comment]
> > > Thanks for your reply. I first installed fairseq using
> > > %sh git clone https://github.com/pytorch/fairseq && cd fairseq && git checkout tags/v0.12.1 && pip install --editable ./
> > > and then I attempted to install stopes using
> > > %sh git clone https://github.com/facebookresearch/stopes.git && cd stopes && pip install '.[mono]'
> > > I should mention that I am trying to do the installation within a Databricks notebook. It does not seem possible to do the installation in editable mode.
> > 
> > 
> > Hi @nicholas-entis, thanks for the context. You'll need to upgrade pip on your databricks notebook in order to install the library (also in editable in mode). Can you try the following:
> > ```
> > %sh /databricks/python3/bin/python -m pip install --upgrade pip
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then try re-running the install command?
> > ```
> > %sh git clone https://github.com/facebookresearch/stopes.git && cd stopes && pip install -e '.[mono]'
> > ```
> 
> I tried your suggestion but got the same error :( I successfully installed pip-22.2.2. I wanted to see if I could do the install in a Google collab notebook, but it seems they don't yet support Python >= 3.8.

Hi @nicholas-entis, I managed to install stopes via a databricks notebook. Can you try maybe following [this example notebook](https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/3738531245964579/3631773718835079/3492704342167123/latest.html)? Hopefully this works!

**Comment by nicholas-entis** [comment]
@heffernankevin Thank you for your help! In the end, I think the issue was the runtime version I was using in Databricks. I encountered the issue when using the 11.0 ML (includes Apache Spark 3.3.0, GPU, Scala 2.12) runtime. When I ran your example notebook with this runtime I got the same error. However, when I switched the runtime to 10.4 LTS (includes Apache Spark 3.2.1, Scala 2.12), it worked.

**Comment by heffernankevin** [comment]
> @heffernankevin Thank you for your help! In the end, I think the issue was the runtime version I was using in Databricks. I encountered the issue when using the 11.0 ML (includes Apache Spark 3.3.0, GPU, Scala 2.12) runtime. When I ran your example notebook with this runtime I got the same error. However, when I switched the runtime to 10.4 LTS (includes Apache Spark 3.2.1, Scala 2.12), it worked.

great!!

**Pull request merged**
